# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
<<<<<<< HEAD
    shield: flux_left
  - board: nice_nano_v2
    shield: flux_right
=======
    shield: iris_left
  - board: nice_nano_v2
    shield: iris_right
>>>>>>> 3ad351252e40f99f3334c21b1cf1f82eb43d0b22
