file_format: "1"
id: flux
name: Flux
type: shield
url: https://github.com/Chrisoyng/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - encoder
siblings:
  - flux_left
  - flux_right
